### ISSUE TITLE
jQuery's on()

### ISSUE THREAD

**Issue by mhulse** [gregschwartz/decimalize-jquery-plugin#1]
Thanks for this plugin, it's been helpful. :+1: 

Not sure if this is worth of a PR, but I changed your plugin from this:

``` js
this.keyup(function() {
```

To this:

``` js
this.on('change keypress paste input', function() {
```

On [line `#4`](https://github.com/gregschwartz/decimalize-jquery-plugin/blob/aba9c771ff93fdcc30dd8163a1aca66b2fba5620/jquery.decimalize.js#L4).

I was running into some issues for when it came to updating text nodes of divs with math relating to the result of the decimalize plugin. Long story short, adding the additional events helped to fix my problem.

**Comment by gregschwartz** [comment]
@mhulse Good idea! Happy to merge a PR, or just make the change myself, whichever you like.

**Comment by mhulse** [comment]
I don't mind doing a PR. Thanks @gregschwartz. :+1:

**Comment by gregschwartz** [comment]
Thanks, just bumped the version number.

**Comment by mhulse** [comment]
Awesome! Thanks @gregschwartz, appreciate the help and the useful code. :+1:

**Comment by mhulse** [comment]
I don't mean to be a bother, and I'm not sure if it makes a difference to the jQuery plugin registry, but you might want to [draft a 1.2.0 release](https://github.com/gregschwartz/decimalize-jquery-plugin/releases) to match the JSON file. :+1: 

Thanks again!

**Comment by gregschwartz** [comment]
Sure @mhulse, happy to do so. Done. Does the jQuery spider not realize that the version has changed without that?

**Comment by mhulse** [comment]
Thanks Greg! I'm not sure about jQuery, but here's a few reasons why I would keep my tags/releases current:
1. Some folks go directly to releases and download the latest, going on the assumption that it's the latest stable code.
2. Bower, a package manager, IIRC (I could be remembering wrong), uses the releases/tags to obtain code. 

Not sure about jQuery, but this WIKI page talks about having a tag:
- [How to publish a plugin in jQuery Plugin Registry](https://github.com/jquery-boilerplate/jquery-boilerplate/wiki/How-to-publish-a-plugin-in-jQuery-Plugin-Registry#step-4---publish-a-version)

Anyway, thanks for doing that! Also, thanks for the helpful code, I really appreciate it! :+1:

**Comment by gregschwartz** [comment]
Good to know, thanks for teaching me!
