### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by mhulse** [gregschwartz/decimalize-jquery-plugin#2]
This might be outside the scope of what you want your code to do, but it might be nice to have a callback function (`onUpdate()`) fire after it's updated the value of the decimal.

**Comment by gregschwartz** [comment]
That is a bit beyond the scope I'd like to handle right now. But if multiple people requested it, it could certainly be added. Thanks!

**Comment by mhulse** [comment]
Thanks for your consideration! :octocat:
